const data = [
  {
    name: "Shirt",
    price: 10,
    desc: "A Plain Shirt",
    img: "./shirt.jpg",
    quantity: 10,
    seller: "X10o5o6",
    rating: 10,
    productID: "1",
  },
  {
    name: "Pant",
    price: 25,
    desc: " A Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem Ipsu",
    img: "./pant.jpg",
    quantity: 5,
    seller: "X1asdao6",
    rating: 10,
    productID: "2",
  },
  {
    name: "Shirt",
    price: 10,
    desc: "A Plain Shirt",
    img: "./shirt.jpg",
    quantity: 10,
    seller: "X10o5o6",
    rating: 10,
    productID: "3",
  },
  {
    name: "Shirt",
    price: 10,
    desc: "A Plain Shirt",
    img: "./shirt.jpg",
    quantity: 10,
    seller: "X10o5o6",
    rating: 10,
    productID: "4",
  },
  {
    name: "Shirt",
    price: 10,
    desc: "A Plain Shirt",
    img: "./shirt.jpg",
    quantity: 10,
    seller: "X10o5o6",
    rating: 10,
    productID: "5",
  },
  {
    name: "Shirt",
    price: 10,
    desc: "A Plain Shirt",
    img: "./shirt.jpg",
    quantity: 10,
    seller: "X10o5o6",
    rating: 10,
    productID: "6",
  },
  {
    name: "Shirt",
    price: 10,
    desc: "A Plain Shirt",
    img: "./shirt.jpg",
    quantity: 10,
    seller: "X10o5o6",
    rating: 10,
    productID: "7",
  },
  {
    name: "Shirt",
    price: 10,
    desc: "  A Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem Ipsu A Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem Ipsu A Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem IpsuA Plain Pant lorem Ipsu",
    img: "./shirt.jpg",
    quantity: 0,
    seller: "X10o5o6",
    rating: 10,
    productID: "8",
  },
];

export default data;
